### ISSUE TITLE
Gluster repository fails

### ISSUE THREAD

**Issue by joelwigley** [DataShades/ckan-aws-templates#4]
When running the setup for the initial service node, it fails because the /etc/yum.repos.d/glusterfs-epel.repo file is referencing an empty repository.

Gluster support should probably be switched to use an OpsWorks App instead. It looks like a more valid repository can be found here: http://buildlogs.centos.org/centos/7/storage/x86_64/gluster-3.7 or via https://wiki.centos.org/SpecialInterestGroup/Storage

**Comment by LinkSDM** [comment]
Gluster build dropped and replaced with NFS stack.
