### ISSUE TITLE
Postgres RDS creation fails

### ISSUE THREAD

**Issue by joelwigley** [DataShades/ckan-aws-templates#6]
Trying to create a new CF stack using https://github.com/DataShades/ckan-aws-templates/blob/master/Datashades-OpsWorks-NFS-CKAN-Stack.json, I get the following error:

11:44:49 UTC+1000	CREATE_FAILED	AWS::RDS::DBInstance	PostgresRDS	MasterUsername pg_dba cannot be used because role names starting with "pg_" are reserved by the PostgreSQL engine

It looks like Postgres 9.6 introduced this restriction on pg_ names.

Aside from updating the template to use an allowed name, it might be worth adding an option to select the Postgres version for the RDS as it may not always be the newest version that is required.

**Comment by LinkSDM** [comment]
Fixed in commit [98827cc](https://github.com/DataShades/ckan-aws-templates/commit/98827cc4348565faffe155cf6bf1cb6826659767) which requires [ckan-cookbook v1.1.2](https://github.com/DataShades/opswx-ckan-cookbook/tree/v1.1.2)
